/**
 * 商户常量
 *
 */
export default {
    STORE_PHOTO_TYPE_CD_DOOR_HEADER:"T",//门头照
    STORE_PHOTO_TYPE_CD_INNER_PHOTO:"I",//内景照
    STORE_CREDENTIALS_CD_BUSINESS_LICENCE:'2',//营业执照
    STORE_CREDENTIALS_CD_AUTHORIZATION_LETTER:'3',// 授权函
    STORE_CREDENTIALS_CD_BUSINESS_CERTIFICATE:'4',// 营业许可证
    STORE_CREDENTIALS_LONG_TIME:'3000-01-01',
}